- name : Configure gsutil and required packages and deploy and execute the payload
  become: true
  become_method: sudo
  hosts: nodes
  gather_facts: no
  force_handlers: True
  tasks:
  - name: Download get-pip file
    get_url:
      url: https://bootstrap.pypa.io/get-pip.py
      dest: /tmp/get-pip.py
      mode: 0750
  - block:
    - name: Install Python3
      yum:
        name: python3
        state: latest
        update_cache: yes
      become: true
      become_method: sudo
    - name: Install GCC
      yum:
        name: gcc
        state: latest
    - name: Install python36-devel
      yum:
        name: python36-devel
        state: latest
    rescue:
    - name: Update yum.. older way
      shell: "sudo yum update -y"
    - name: Install Python-devel.. older way
      shell: "sudo yum install python3 python36-devel -y"
    - name: Install GCC .. older way
      shell: "sudo yum install gcc -y"
    tags:
        - devel  
  - block:
    - name: Install Python packages
      pip:
        name: "{{ item }}"
      with_items:
        - gsutil
        - netifaces
        - netaddr
        - mongoengine
        - psutil
        - python-dotenv
        - dnspython
        - pyasn1==0.4.6
    rescue:
    - name: Install python packages
      shell: "sudo pip3 install {{ item }}"
      with_items:
        - gsutil
        - netifaces
        - netaddr
        - mongoengine
        - psutil
        - python-dotenv
        - dnspython
        - pyasn1==0.4.6

  - name: Configure gsutil credentials
    template:
      src: "ansible/gcp/templates/.boto.j2"
      dest: "~/.boto"

  - name: <==Deploy payload==>
    copy:
      src: "../payloads/footprint.py"
      dest: "/tmp/footprint.py"
    tags:
      - deploy

  - name: <==Executing payload==>
    shell: "python3 /tmp/footprint.py {{ project }} '{{ mongodb }}' {{ inventory_hostname }}"
    register: st
    become: True
    tags:
      - exec

  - name: Debug
    debug:
      var: st
    tags:
      - msg