- hosts: all
  gather_facts: true
- name: executing redhat 8 playbook
  import_playbook: gcp_env_setup_redhat_7.yaml
  when: ansible_distribution == "RedHat" and ansible_distribution_major_version == '7'
- name: executing redhat 8 playbook
  import_playbook: gcp_env_setup_redhat_8.yaml
  when: ansible_distribution == "RedHat" and ansible_distribution_major_version >= '8'
- name: executing ubuntu 16.04 playbook
  import_playbook: gcp_env_setup_ubuntu_16.yaml
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == '16'