version: '3.1'

services:
  cassandra:
    image: docker.io/bitnami/cassandra:4.0
    volumes:
      - cassandra_data:/bitnami
    environment:
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=cassandra
      # By default, Cassandra autodetects the available host memory and takes as much as it can.
      # Therefore, memory options are mandatory if multiple Cassandras are launched in the same node.
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=200M
  app:
    build: .
    ports:
      - 8000:80
    environment:
      CASS_PASSWORD: "mypassword"
      CASS_USER: "myuser"
      CASS_DB: "cassandra"
      BASE_URL: http://15.207.235.96:8000/api
    depends_on:
     - cassandra

volumes:
  cassandra_data:
    driver: local
  cassandra2_data:
    driver: local
