- name : Starting migration
  become: true
  become_method: sudo
  hosts: nodes
  gather_facts: no
  force_handlers: True
  tasks:
  - name: <== Deploy payload ==>
    copy:
      src: "../payloads/start_dd_azure.py"
      dest: "/tmp/start.py"
  - name: <== Executing payload ==>
    shell: "python /tmp/start.py {{ url }} '{{ sas }}' '{{ mongodb }}' {{ project }}"
    register: st
    become: True
  - name: Message
    debug:
      var: st
