- name : Configure aws-cli and required packages and deploy and execute the payload
  become: true
  become_method: sudo
  hosts: nodes
  gather_facts: no
  force_handlers: True
  tasks:
  - name: mirrorlist
    shell: "sudo sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*"
  - name: mirrorlist
    shell: "sudo sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*"  
  - name: yum update
    shell: "sudo yum update -y"    
  - name: Download get-pip file
    get_url:
      url: https://bootstrap.pypa.io/get-pip.py
      dest: /tmp/get-pip.py
      mode: 0750
  - block:
    - name: Install Python3
      yum:
        name: python3
        state: latest
        update_cache: yes
      become: true
      become_method: sudo
    - name: Install GCC
      yum:
        name: gcc
        state: latest
    - name: Install python36-devel
      yum:
        name: python36-devel
        state: latest
    rescue:
    - name: Update yum.. older way
      shell: "sudo yum update -y"
    - name: Install Python-devel.. older way
      shell: "sudo yum install python3 python36-devel -y"
    - name: Install GCC .. older way
      shell: "sudo yum install gcc -y"
    tags:
        - devel

          #  - name: Install pip
          #    shell: "sudo python /tmp/get-pip.py"
  
  - block:
    - name: Install Python packages
      pip:
        name: "{{ item }}"
      with_items:
        - awscli
        - netifaces
        - netaddr
        - mongoengine
        - psutil
        - python-dotenv
        - dnspython
    rescue:
    - name: Install python packages
      shell: "sudo pip3 install {{ item }}"
      with_items:
        - awscli
        - netifaces
        - netaddr
        - mongoengine
        - psutil
        - python-dotenv
        - dnspython

  - name: Create .aws directory
    file:
      path: "~/.aws/"
      state: directory
      mode: 0755

  - name: Configure awscli credentials
    copy:
      src: "~/.aws/credentials"
      dest: "~/.aws/credentials"

  - name: Configure aws region
    copy:
      src: "~/.aws/config"
      dest: "~/.aws/config"

  - name: <==Deploy payload==>
    copy:
      src: "../payloads/footprint.py"
      dest: "/tmp/footprint.py"
    tags:
      - deploy

  - name: <==Executing payload==>
    shell: "python3 /tmp/footprint.py {{ project }} '{{ mongodb }}' {{ inventory_hostname }}"
    register: st
    become: True
    tags:
      - exec

  - name: Debug
    debug:
      var: st
    tags:
      - msg